blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.myblog, name='myblog'),  
     path('<int:blog_id>/',views.details, name='details'),  
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class ProjectBlog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=240)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank='TRUE')
    
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProjectBlog

def myblog(request):
    blog_count = ProjectBlog.objects.count()
    projects = ProjectBlog.objects.order_by('-date')
    return render(request, 'blog/myblog.html', {'myblogproject': projects})

def details(request, blog_id):
    blogs = get_object_or_404(ProjectBlog, pk=blog_id)
    return render(request, 'blog/details.html', {'blogs': blogs})

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'myproject': projects})

blog/templates/blog/details.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blogs.title }}</h1>
<h5  class="text-center text-muted mb-5">{{ blogs.date|date:'F d Y' }}</h5>
<p> {{ blogs.description }} </p>

{% endblock %}

blog/templates/blog/myblog.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<h3 id="blogtitle" class="font-weight-bold text-center">My Blog</h3>

<h3 class="text-center mb-5">Akash has written {{ myblogproject.count }} article{{ myblogproject.count|pluralize }}</h3>

{% for item in myblogproject%}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:details' item.id%}">
        <h3>{{ item.title }}</h3>
    </a>
    <h5 class="text-muted">{{ item.date|date:'M d Y' }}</h5>
    <h4>{{ item.description|truncatechars:100 }}</h4>
    </div>
</div>
{% endfor %}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      
  <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
 
  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static 'portfolio/icon.png' %}">

    <title>Blogs World</title>
  </head>
  <body>
      
        <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'portfolio/icon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Akash's Logo">
        <span>Akash Guha</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/Resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/akash-guha-12a2a4112/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/_aka_guha" target="_blank">Twitter</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="https://www.facebook.com/ConnorG007/" target="_blank">Facebook</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:myblog' %}" class="btn btn-primary" target="_blank">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}


<div class="row justify-content-center my-3">
  <div class="col-5">
<img id="profilepic" src="{% static 'portfolio/SuitsMe.JPG' %}" class="img-fluid" >
  </div>
</div>
<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Welcome to my Website</h1>
    <h5>Enjoy reading my articles, follow me up on my socials for daily updates.</h5>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
{% for item in myproject %}
    <div class="col-lg-4 col-md-6">    
   
        {% if item.url%}
        <a href="{{ item.url }}" target="_blank" >
              <img src="{{ item.image.url }}" class="img-fluid mb-2" >
        </a>
        
        {% else %}
        <img src="{{ item.image.url }}" class="img-fluid mb-2" >
    {% endif %}
        
    <h3>{{ item.title }}</h3>
    <p>{{ item.description }}</p>
    </div>
{% endfor %}
</div>
{% endblock %}